### ISSUE TITLE
Getting It is not currently possible to manually set the aspect on 3D axes error

### ISSUE THREAD

**Issue by mhjor70** [mo-geometry/hopf_fibration#1]
Need a lil help.. i am using python 3.8 and latest libraries from pip.

**Comment by mo-geometry** [comment]
In the hopf1.py script line 20: comment out 

```
# ax.axis('equal')
```

it should run then

**Comment by mhjor70** [comment]
I keep getting this one.

C:\Users\mikeh\hopf-fibration>python hopf1.py
Traceback (most recent call last):
  File "hopf1.py", line 73, in <module>
    fig, lines, points = genFigure(h.fiber, h.s2path)
  File "hopf1.py", line 20, in genFigure
    ax.axis('equal')
  File "D:\Python\Python38\lib\site-packages\matplotlib\axes\_base.py", line 1633, in axis
    self.set_aspect('equal', adjustable='datalim')
  File "D:\Python\Python38\lib\site-packages\matplotlib\axes\_base.py", line 1263, in set_aspect
    raise NotImplementedError(
NotImplementedError: It is not currently possible to manually set the aspect on 3D axes

________________________
Michele (Mike) Hjorleifsson
Phone: (772) 224-8913 x4


[cid:image002.jpg@01D64F2A.8692D9C0]

**Comment by mo-geometry** [comment]
The problem you are having is a known one, see [matplotlib/issues](https://github.com/matplotlib/matplotlib/issues/16568)

It requires you to remove [this line](https://github.com/mo-geometry/hopf-fibration/blob/master/hopf1.py#L20) from the code. 

Delete the line and the script should compile ok.

**Comment by mhjor70** [comment]
That did the trick, thanks

________________________
Michele (Mike) Hjorleifsson
Phone: (772) 224-8913 x4


[cid:image002.jpg@01D65005.B026A6F0]
