### ISSUE TITLE
Figure 3 crashes after generating the plots.

### ISSUE THREAD

**Issue by MrCherub** [mo-geometry/hopf_fibration#2]
After calculating 100% of the S1 phase grids and then generating 100% of the phase plots it immediately crashes.

**Comment by mo-geometry** [comment]
Hi man - I haven't looked at this code in ages. I am planning a major update but it's going to take a few months at least. 

Regarding this bug, I can think of two things to check. 

The first is the memory resources being used. 
line 12; time_resolution=2**16
line 82; dim = (2 ** 6 + 2 ** 5 + 2 ** 4, 2 ** 7)  # phase grid dimensions
try reducing these numbers 

The second check is the version of matplotlib. This code might not be compatible with the most recent versions of matplotlib. So either try install an earlier version or debug line by line and see where the error happens, and update accordingly.

**Comment by MrCherub** [comment]
> Hi man - I haven't looked at this code in ages. I am planning a major update but it's going to take a few months at least.
> 
> Regarding this bug, I can think of two things to check.
> 
> The first is the memory resources being used. line 12; time_resolution=2**16 line 82; dim = (2 ** 6 + 2 ** 5 + 2 ** 4, 2 ** 7) # phase grid dimensions try reducing these numbers
> 
> The second check is the version of matplotlib. This code might not be compatible with the most recent versions of matplotlib. So either try install an earlier version or debug line by line and see where the error happens, and update accordingly.

Okay I'll try that.
